[package]
name = "gfx_text"
version = "0.13.2"
authors = ["Kagami Hiiragi <kagami@genshiken.org>"]
description = "Draw text for gfx using freetype."
keywords = ["gfx", "graphics", "text", "freetype", "font"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/PistonDevelopers/gfx_text"
repository = "https://github.com/PistonDevelopers/gfx_text.git"
documentation = "http://docs.piston.rs/gfx_text/gfx_text/"

[dependencies]
gfx = "0.13.0"
freetype-rs = "0.11"

[features]
default = ["include-font"]
include-font = []

### For examples

[dev-dependencies]
piston = "0.26.0"
pistoncore-glutin_window = "0.31.0"
gfx_device_gl = "0.12.0"
shader_version = "0.2.1"
glutin = "0.6.2"
#log = "*"
#env_logger = "*"
